//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestsForSimmetrics.Properties {
    using System.CodeDom.Compiler;
    using System.Configuration;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;

    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    sealed partial class Settings : ApplicationSettingsBase {
        static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));

        static public Settings Default { get { return defaultInstance; } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [
            DefaultSettingValue(
                "CHRISTOPHER PARKINSON,CHRIS PARKINSON, 0.500,0.00,0.714,0.258,0.50,0.688,0.789,0." +
                "765,0.714,0.738,0.750,0.50,0.293,0.333,0.50,1.0,0.50")]
        public string blockDistance1 { get { return ((string)(this["blockDistance1"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [
            DefaultSettingValue(
                "RUTH KATHERINE LANHAM,RUTH KATHERINE PARKINSON, 0.667,0.00,0.875,0.314,0.667,0.63" +
                "4,0.638,0.651,0.708,0.792,0.612,0.667,0.423,0.500,0.667,0.80,0.667")]
        public string blockDistance2 { get { return ((string)(this["blockDistance2"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [
            DefaultSettingValue(
                "SHACKLEFORD,SHACKELFORD,0.970,0.982,1.00,0.165,0.090,0.818,0.727,0.01,0.818,0.909" + ",0.692,0.0,0.0")]
        public string jaroName1 { get { return ((string)(this["jaroName1"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("DUNNINGHAM,CUNNIGHAM,0.896,0.896,0.90,0.144,0.00,0.833,0.778,0.01,0.800,0.850,0.5" + "22,0.0,0.0")
            ]
        public string jaroName2 { get { return ((string)(this["jaroName2"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("NICHLESON,NICHULSON,0.926,0.956,1.00,0.136,0.00,0.778,0.667,0.01,0.778,0.889,0.63" + "6,0.0,0.0")]
        public string jaroName3 { get { return ((string)(this["jaroName3"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JONES,JOHNSON,0.790,0.832,0.714,0.093,0.00,0.600,0.400,0.01,0.429,0.571,0.250,0.0" + ",0.0")]
        public string jaroName4 { get { return ((string)(this["jaroName4"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("MASSEY,MASSIE,0.889,0.933,1.00,0.093,0.00,0.75,0.767,0.01,0.667,0.833,0.50,0.0,0." + "0")]
        public string jaroName5 { get { return ((string)(this["jaroName5"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ABROMS,ABRAMS,0.889,0.922,1.00,0.093,0.00,0.667,0.933,0.01,0.833,0.917,0.625,0.0," + "0.0")]
        public string jaroName6 { get { return ((string)(this["jaroName6"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JERALDINE,GERALDINE,0.926,0.926,1.00,0.136,0.00,0.889,0.956,0.01,0.889,0.944,0.72" + "7,0.0,0.0")]
        public string jaroName7 { get { return ((string)(this["jaroName7"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("SHACKLEFORD,SHACKELFORD,0.818,0.818,0.818,0.818")]
        public string swName1 { get { return ((string)(this["swName1"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("DUNNINGHAM,CUNNIGHAM,0.833,0.833,0.833,0.833")]
        public string swName2 { get { return ((string)(this["swName2"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("NICHLESON,NICHULSON,0.778,0.778,0.778,0.778")]
        public string swName3 { get { return ((string)(this["swName3"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("SHACKLEFORD,SHACKELFORD,0.727,0.727,0.727,0.727")]
        public string swgName1 { get { return ((string)(this["swgName1"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("DUNNINGHAM,CUNNIGHAM,0.778,0.778,0.778,0.778")]
        public string swgName2 { get { return ((string)(this["swgName2"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ABROMS,ABRAMS,0.933,0.933,0.933,0.933")]
        public string swgName6 { get { return ((string)(this["swgName6"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JERALDINE,GERALDINE,0.956,0.956,0.956,0.956")]
        public string swgName7 { get { return ((string)(this["swgName7"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("NICHLESON,NICHULSON,0.667,0.667,0.667,0.667")]
        public string swgName3 { get { return ((string)(this["swgName3"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JONES,JOHNSON,0.400,0.400,0.400,0.400")]
        public string swgName4 { get { return ((string)(this["swgName4"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("MASSEY,MASSIE,0.767,0.767,0.767,0.767")]
        public string swgName5 { get { return ((string)(this["swgName5"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JONES,JOHNSON,0.600,0.600,0.600,0.600")]
        public string swName4 { get { return ((string)(this["swName4"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("MASSEY,MASSIE,0.750,0.750,0.750,0.750")]
        public string swName5 { get { return ((string)(this["swName5"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ABROMS,ABRAMS,0.667,0.667,0.667,0.667")]
        public string swName6 { get { return ((string)(this["swName6"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JERALDINE,GERALDINE,0.889,0.889,0.889,0.889")]
        public string swName7 { get { return ((string)(this["swName7"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("SHACKLEFORD,SHACKELFORD,0.727,0.727,0.727,0.727,0.727,0.727,0.727,0.727")]
        public string swgaName1 { get { return ((string)(this["swgaName1"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("DUNNINGHAM,CUNNIGHAM,0.778,0.778,0.778,0.778,0.778,0.778,0.778,0.778")]
        public string swgaName2 { get { return ((string)(this["swgaName2"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("NICHLESON,NICHULSON,0.667,0.667,0.667,0.667,0.667,0.667,0.667,0.667")]
        public string swgaName3 { get { return ((string)(this["swgaName3"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JONES,JOHNSON,0.400,0.400,0.400,0.400,0.400,0.400,0.400,0.400")]
        public string swgaName4 { get { return ((string)(this["swgaName4"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("MASSEY,MASSIE,0.767,0.767,0.767,0.767,0.767,0.767,0.767,0.767")]
        public string swgaName5 { get { return ((string)(this["swgaName5"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ABROMS,ABRAMS,0.933,0.933,0.933,0.933,0.933,0.933,0.933,0.933")]
        public string swgaName6 { get { return ((string)(this["swgaName6"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("JERALDINE,GERALDINE,0.956,0.956,0.956,0.956,0.956,0.956,0.956,0.956")]
        public string swgaName7 { get { return ((string)(this["swgaName7"])); } }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [
            DefaultSettingValue(
                "CHRIS PARKINSON 10 ADOM COURT 61 THIKET ROAD SUTTON SM1 4PX,CHRISTOPHER lARKINSON" +
                " FLAT 10 ADAM COURT 59-61 THICKET ROAD SUTTON, 0.725, 0.725, 0.725, 0.725, 0.725" +
                ", 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725, 0.725")]
        public string swgaName8 { get { return ((string)(this["swgaName8"])); } }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [
            DefaultSettingValue(
                "CHRIS PARKINSON 10 ADOM COURT 61 THIKET ROAD SUTTON SM1 4PX,CHRISTOPHER lARKINSON" +
                " FLAT 10 ADAM COURT 59-61 THICKET ROAD SUTTON, 0.381, 0.0, 0.894, 0.684, 0.381, " +
                "0.612, 0.693, 0.699, 0.621, 0.644, 0.605, 0.381, 0.213, 0.235, 0.364, 0.860,0.40" + "")]
        public string blockDistance3 { get { return ((string)(this["blockDistance3"])); } set { this["blockDistance3"] = value; } }
    }
}