//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LEMResources.rc
//
#define AID_HORIZON                     11
#define AID_HORIZON2                    12
#define AID_ALTITUDE1                   13
#define AID_ENTRY_MODE_SWITCH			14
#define AID_FDAI_SWITCHES				15
#define AID_ECS_INDICATOR_SWITCH		16
#define AID_EVENT_TIMER_SWITCHES		17
#define AID_DSKY_LIGHTS					18
#define AID_DSKY_DISPLAY                19
#define AID_DSKY_KEY                    20
#define AID_DSKY2_LIGHTS				21
#define AID_DSKY2_DISPLAY               22
#define AID_DSKY2_KEY					23
#define AID_SWITCH_PANEL_LEFT           24
#define AID_GAUGES_CENTER               25
#define AID_ALTIMETER                   27
#define AID_GMETER                      28
#define AID_THRUSTMETER                 29
#define AID_SPS                         30
#define AID_ABORT_ROW                   31
#define AID_EDS                         32
#define AID_ROT_PWR                     33
#define AID_MISSION_CLOCK               34
#define AID_SWITCH_PANEL_RIGHT          35
#define AID_ABORT                       36
#define AID_BMAG_SWITCHES				37
#define AID_MASTER_ALARM2				38
#define AID_dVTHRUST_SWITCHES			39
#define AID_SWITCH_SEP                  40
#define AID_CONTACT                     41
#define AID_MASTER_ALARM                42
#define AID_CWS_LIGHTS_LEFT				43
#define AID_CWS_LIGHTS_RIGHT			44
#define AID_EVENT_TIMER					45
#define AID_MASTER_ALARM3               46
#define AID_RCS_HELIUM1_TALKBACK		47
#define AID_RCS_HELIUM2_TALKBACK		48
#define AID_RCS_PROP1_TALKBACK			49
#define AID_RCS_PROP2_TALKBACK			50

#define AID_ABORT_BUTTON                51
#define AID_FUEL_DIGIT                  52
#define AID_SM_RCS_PANEL1               53
#define AID_SM_RCS_MODE                 54
#define AID_SPS_GIMBAL_SWITCHES         55
#define AID_TLI_SWITCH                  56
#define AID_CM_RCS_SWITCH               57
#define AID_CMC_SWITCH                  58
#define AID_SC_SWITCH                   59


#define AID_P16                         62
#define AID_SIVB_RCS                    63
#define AID_SIVB_GIMBAL                 64
#define AID_P17                         65
#define AID_ELS_SWITCHES                66
#define AID_P18                         67
#define AID_CMD_SWITCH                  68
#define AID_CMP_SWITCH                  69
#define AID_FCSM_SWITCH                 71
#define AID_P19                         72
#define AID_DIRECT_ULLAGE_THRUST_ON_LIGHT 73
#define AID_LV_ENGINE_LIGHTS            74
#define AID_LV_TANK_GAUGES              75

#define AID_EMS                         77
#define AID_SWITCH_JET                  78
#define AID_MAIN_RELEASE_SWITCH         79



#define AID_LV_SWITCHES					83
#define AID_DOCKING_PROBE_SWITCH        84
#define AID_P21                         85
#define AID_SEQUENCERSWITCHES           86
#define AID_LEM_POWER_SWITCH            87
#define AID_SMRCS_HELIUM1_SWITCHES      89


#define AID_SMRCS_HELIUM2_SWITCHES      92
#define AID_PRIM_PRPLNT_SWITCHES        93
#define AID_P24                         94
#define AID_P25                         95
#define AID_SEC_PRPLT_SWITCHES          96
#define AID_P27                         98
#define AID_P28                         99
#define AID_P29                         100
#define IDB_MAINPANEL                   101
#define IDB_PANEL2                      102
#define IDB_PANEL3                      103
#define IDB_DIAL1                       104
#define IDB_NAVBUTTON                   105
#define IDB_LIGHT1                      106
#define IDB_INDICATOR                   107
#define IDB_HORIZON                     108
#define IDB_SLIDER1                     109
#define IDB_SWITCH2                     152
#define IDB_SWITCH3                     153
#define IDB_VPITCH                      154
#define IDB_VBANK                       155
#define IDB_VYAW                        156
#define IDB_LEVER1                      157
#define AID_PILOT1                      158
#define AID_GAUGES1                     160
#define AID_VELOCITY1                   161
#define IDB_ROT_KNOB                    163
#define IDB_NEEDLE                      165
#define IDB_DIGITAL                     166
#define IDB_HORIZON2                    170
#define IDB_SWITCHUP                    171
#define IDB_SWLEVER                     172
#define IDB_SECSWITCH                   173
#define IDB_LV_ENG                      174
#define IDB_LAUNCH                      175
#define IDB_ABORT                       176
#define IDB_ANNUN                       177
#define IDB_LIGHTS2                     178
#define IDB_HEADING                     179
#define IDB_ANLG_ALT                    180
#define IDB_ANLG_GMETER                 181
#define IDB_THRUST                      182
#define IDB_LEM_MAIN_PANEL              183
#define IDB_CONTACT                     184
#define IDB_ABORTSWITCH                 185
#define IDB_LIGHTSWITCH                 186
#define IDB_ABORTILMSW                  200


#define IDB_MASTER_ALARM                203
#define IDB_MASTER_ALARM_BRIGHT         204
#define IDB_DSKY_LIGHTS                 205
#define IDB_DSKY_NUMBERS                206
#define IDB_ILMPANEL                    207
#define IDB_ILMSWLEVER                  209
#define IDB_ILMSECSWITCH                210
#define IDB_ILM_LV_ENG                  211
#define IDB_ILMLAUNCH                   212
#define IDB_ILMABORT                    213
#define IDB_ILMANNUN                    214
#define IDB_ILMLIGHTS2                  215
#define IDB_ILMMASTER_ALARM             216
#define IDB_ILMDSKY_LIGHTS              217
#define IDB_ILMSWITCHUP                 218
#define IDB_ILMLEMPANEL                 219
#define IDB_ILMDCKPANEL                 220
#define IDB_MAINDCKPANEL                221
#define IDB_FCSM                        222
#define IDB_SEQUENCERSWITCHES           223
#define IDB_ILMGUARDSWITCH              224
#define IDB_CABIN                       240
#define IDB_ALLROUND                    241
#define IDB_ILMCABIN                    242
#define IDB_ILMALLROUND                 243
#define IDB_THREEPOSSWITCH              244
#define IDB_CW                          245
#define IDB_ILMCW                       246
#define IDB_SWITCH1                     247
#define IDB_LEMSWITCH1                  248
#define IDB_ILMSWITCH1                  249
#define IDB_ILMLEMSWITCH1               250
#define IDB_ILMLEMSWITCH2               251
#define IDB_LEMSWITCH2                  252
#define IDB_LEMSWITCH3                  253
#define IDB_ILMLEMSWITCH3               254
#define IDB_FDAI                        255
#define IDB_ECSG                        256
#define IDB_ILMECSG                     257
#define IDB_ILMFCSM                     268
#define IDB_ILMTHREEPOSSWITCH           269
#define IDB_MFDFRAME                    270
#define IDB_MFDPOWER                    271
#define IDB_DOCKINGSWITCHES             272
#define IDB_MFDFRAME_ILM                273
#define IDB_MFDPOWER_ILM                274
#define IDB_DOCKINGSWITCHES_ILM         275
#define IDB_ILMMAINPANEL_LEFT           276
#define IDB_ILMMAINPANEL_RIGHT          277
#define IDB_MAINPANEL_LEFT              278
#define IDB_MAINPANEL_RIGHT             279
#define IDB_ROTATIONALSWITCH            280
#define IDB_SWITCHGUARDS                281
#define IDB_LMTHREEPOSLEVER             287
#define IDB_LM3POSSWITCH                288
#define IDB_LMTHREEPOSSWITCH            288
#define AID_FUEL_DIGITD                 301
#define AID_VELOCITY2                   302
#define AID_ALTITUDE2                   303
#define AID_VSI2                        304
#define AID_P30                         400
#define AID_CABIN_PRESS                 401

#define AID_FUELCELLRADIATORSINDICATORS 403
#define AID_P31                         404

#define AID_P32                         406

#define AID_P33                         408
#define AID_P34                         409
#define AID_FUELCELLREACTANTSSWITCHES   410
#define AID_P35                         411
#define AID_P36                         412
#define AID_CYROTANKSWITCHES            413
#define AID_CM_RCS_LOGIC                414
#define AID_SMRCS_FUEL                  416
#define AID_SPS_FUEL                    417
#define AID_EMS_SWITCH                  418
#define AID_BUS_PANEL                   419
#define AID_05G_LIGHT                   420
#define AID_SPS_LIGHT                   421
#define AID_SPS_INJ_VLV                 422
#define AID_AUTO_LIGHT                  423
#define AID_BUS_LIGHT                   425
#define AID_CABIN_LIGHT                 426
#define AID_CABININDICATORS             427
#define AID_FUEL_DIGIT2                 428
#define AID_DESCENT_HE                  429
#define AID_ENG_ARM                     430
#define AID_EXPLOSIVE_DEVICES1          431
#define AID_LGC_THRUSTER_QUADS          432
#define AID_RCS_SYSTEMA_SYSTEMB         433
#define AID_MAIN_SOV_SWITCHES           434
#define AID_LANDING_GEAR_SWITCH         435
#define AID_ENGINE_GIMBAL_SWITCH        436
#define AID_ASCENT_HE                   437
#define AID_EXPLOSIVE_DEVICES2          438
#define AID_ATTITUDE_CONTROL_SWITCHES   440
#define AID_ENG_FUEL_TEMP               441
#define AID_ENG_FUEL_PRESS              442
#define AID_ENG_THRUST                  443
#define AID_RCS_TEMP                    444
#define AID_FDAI                        445
#define AID_CRSFD_SWITCH                446
#define AID_CABIN_FAN_SWITCH            447
#define AID_PTT_SWITCH                  448
#define AID_RCS_SYS_AB                  449
#define AID_XPOINTER_SWITCH             450
#define AID_PANEL1_1                    451
#define AID_GUID_CONT_SWITCH            452
#define AID_ALT_RNG_MON                 453
#define AID_SHIFT_SWITCH                454
#define AID_ENGINE_THRUST_CONT          455
#define AID_PROP_MON_SWITCHES           456
#define AID_ACA_PROP_SWITCH             457
#define AID_PANEL2_1                    458
#define AID_DESCENT_ENGINE_SWITCH       459
#define AID_SLEW_RATE_SWITCH            460
#define AID_DEAD_BAND_SWITCH            461
#define AID_IMU_CAGE_SWITCH             462
#define AID_SIDE_PANEL_SWITCH           463
#define AID_XPOINTER2_SWITCH            464
#define AID_AUDIO_CONT_SWITCH           465
#define AID_RELAY_AUDIO_SWITCH          470
#define AID_CABIN_PRESS_SWITCH          471
#define AID_HATCH_SWITCH                472
#define AID_EVA_SWITCH                  473
#define AID_RCS_PRESS                   474
#define AID_RCS_QTY                     475
#define AID_ECS_GAUGES                  476
#define AID_COAS                        477
#define AID_PANEL4_SWITCH1              478
#define AID_PANEL4_SWITCH2              479
#define AID_PANEL4_SWITCH3              480
#define AID_PANEL4_SWITCH4              481
#define AID_EMS_KNOB                    482
#define AID_EMS_DISPLAY                 483
#define AID_MFDDOCK                     484
#define AID_MFDDOCK_POWER               485
#define AID_RCS_INDICATORS              486
#define IDB_CSM_MAIN_PANEL              487
#define IDB_CSM_LEFT_PANEL              488
#define IDB_CSM_RIGHT_PANEL             489
#define IDB_CSM_LEFT_RNDZ_WINDOW        490
#define IDB_CSM_RIGHT_RNDZ_WINDOW       491
#define IDB_CSM_HATCH_WINDOW            492
#define IDB_CSM_LOWER_PANEL             493
#define AID_CYROTANKINDICATORS          494
#define IDB_NEEDLE1                     495
#define AID_FUELCELLREACTANTSINDICATORS 502
#define AID_FUELCELLINDICATORS          503
#define AID_FUELCELLINDICATORSSWITCH    504
#define AID_FUELCELLHEATERSSWITCHES     505
#define AID_FUELCELLRADIATORSSWITCHES   506
#define AID_FUELCELLPHRADTEMPINDICATORS 507
#define AID_SEPARATIONSWITCHES          508
#define AID_XPOINTER                    509
#define AID_SUITCABINDELTAPMETER        510
#define IDB_SUITCABINDELTAPMETER        511
#define AID_SUITCOMPRDELTAPMETER        512
#define AID_FUELCELLPURGESWITCHES       513
#define AID_FUELCELLLATCHSWITCHES       514
#define AID_FUELCELLPUMPSSWITCHES       515
#define IDB_THREEPOSSWITCH305           516
#define AID_SUITCOMPRESSORSWITCHES      517
#define IDB_LEM_RIGHT_WINDOW            518
#define IDB_LEM_LEFT_WINDOW             519
#define AID_SBAND_NORMAL_SWITCHES       520
#define IDB_LMABORTBUTTON               521
#define IDB_LMMFDFRAME                  522
#define AID_MFDLEFT                     523
#define AID_MFDRIGHT                    524
#define IDB_LEM_LPD_WINDOW              525
#define AID_MODECONTROL                 526
#define AID_CAUTIONWARNING_SWITCHES		527
#define AID_MISSION_TIMER_SWITCHES		528
#define IDB_DSKY_DISP                   529
#define AID_FDAI_RIGHT				    530
#define IDB_FDAI_ROLLINDICATOR			531
#define IDB_FDAI_ROLL					532
#define IDB_CWS_LIGHTS					533
#define IDB_EVENT_TIMER					534

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        289
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           10001
#endif
#endif
